server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wiselyman/Spring-Cloud-Bus-Demo.git
          search-paths: config-files
    stream:
      kafka:
        binder:
          brokers: 192.168.1.222

#management.endpoints.web.exposure.include: '*'
management.endpoints.web.exposure.include: bus-refresh


