spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wiselyman/Spring-Cloud-Bus-Demo.git
          search-paths: config-files
server:
  port: 8888


